export interface City {
  name: string;
  zip: string;
}

export interface Province {
  name: string;
  cities: City[];
}

export const PH_LOCATION_DATA: Province[] = [
  { name: "Abra", cities: [{ name: "Bangued", zip: "2800" }, { name: "Bucay", zip: "2805" }, { name: "Dolores", zip: "2801" }] },
  { name: "Agusan del Norte", cities: [{ name: "Butuan City", zip: "8600" }, { name: "Cabadbaran City", zip: "8605" }] },
  { name: "Agusan del Sur", cities: [{ name: "Prosperidad", zip: "8500" }, { name: "Bayugan City", zip: "8502" }] },
  { name: "Aklan", cities: [{ name: "Kalibo", zip: "5600" }, { name: "Malay (Boracay)", zip: "5608" }] },
  { name: "Albay", cities: [{ name: "Legazpi City", zip: "4500" }, { name: "Tabaco City", zip: "4511" }, { name: "Ligao City", zip: "4504" }] },
  { name: "Antique", cities: [{ name: "San Jose de Buenavista", zip: "5700" }] },
  { name: "Apayao", cities: [{ name: "Kabugao", zip: "3809" }] },
  { name: "Aurora", cities: [{ name: "Baler", zip: "3200" }] },
  { name: "Basilan", cities: [{ name: "Isabela City", zip: "7300" }, { name: "Lamitan City", zip: "7302" }] },
  { name: "Bataan", cities: [{ name: "Balanga City", zip: "2100" }, { name: "Dinalupihan", zip: "2110" }, { name: "Mariveles", zip: "2105" }] },
  { name: "Batanes", cities: [{ name: "Basco", zip: "3900" }] },
  { name: "Batangas", cities: [{ name: "Batangas City", zip: "4200" }, { name: "Lipa City", zip: "4217" }, { name: "Tanauan City", zip: "4232" }, { name: "Sto. Tomas City", zip: "4234" }, { name: "Nasugbu", zip: "4231" }] },
  { name: "Benguet", cities: [{ name: "Baguio City", zip: "2600" }, { name: "La Trinidad", zip: "2601" }, { name: "Itogon", zip: "2604" }] },
  { name: "Biliran", cities: [{ name: "Naval", zip: "6543" }] },
  { name: "Bohol", cities: [{ name: "Tagbilaran City", zip: "6300" }, { name: "Panglao", zip: "6340" }] },
  { name: "Bukidnon", cities: [{ name: "Malaybalay City", zip: "8700" }, { name: "Valencia City", zip: "8709" }] },
  { name: "Bulacan", cities: [{ name: "Malolos City", zip: "3000" }, { name: "Meycauayan City", zip: "3020" }, { name: "San Jose del Monte City", zip: "3023" }, { name: "Marilao", zip: "3019" }, { name: "Baliuag City", zip: "3006" }] },
  { name: "Cagayan", cities: [{ name: "Tuguegarao City", zip: "3500" }, { name: "Aparri", zip: "3515" }] },
  { name: "Camarines Norte", cities: [{ name: "Daet", zip: "4600" }] },
  { name: "Camarines Sur", cities: [{ name: "Naga City", zip: "4400" }, { name: "Iriga City", zip: "4431" }, { name: "Pili", zip: "4418" }] },
  { name: "Camiguin", cities: [{ name: "Mambajao", zip: "9100" }] },
  { name: "Capiz", cities: [{ name: "Roxas City", zip: "5800" }] },
  { name: "Catanduanes", cities: [{ name: "Virac", zip: "4800" }] },
  { name: "Cavite", cities: [{ name: "Imus City", zip: "4103" }, { name: "Bacoor City", zip: "4102" }, { name: "Dasmariñas City", zip: "4114" }, { name: "Tagaytay City", zip: "4120" }, { name: "Cavite City", zip: "4100" }, { name: "General Trias City", zip: "4107" }, { name: "Trece Martires City", zip: "4109" }, { name: "Silang", zip: "4118" }] },
  { name: "Cebu", cities: [{ name: "Cebu City", zip: "6000" }, { name: "Mandaue City", zip: "6014" }, { name: "Lapu-Lapu City", zip: "6015" }, { name: "Talisay City", zip: "6045" }, { name: "Danao City", zip: "6004" }, { name: "Toledo City", zip: "6038" }, { name: "Carcar City", zip: "6019" }, { name: "Naga City", zip: "6037" }] },
  { name: "Cotabato", cities: [{ name: "Kidapawan City", zip: "9400" }] },
  { name: "Davao de Oro", cities: [{ name: "Nabunturan", zip: "8800" }] },
  { name: "Davao del Norte", cities: [{ name: "Tagum City", zip: "8100" }, { name: "Panabo City", zip: "8105" }, { name: "Samal City", zip: "8119" }] },
  { name: "Davao del Sur", cities: [{ name: "Davao City", zip: "8000" }, { name: "Digos City", zip: "8002" }] },
  { name: "Davao Occidental", cities: [{ name: "Malita", zip: "8012" }] },
  { name: "Davao Oriental", cities: [{ name: "Mati City", zip: "8200" }] },
  { name: "Dinagat Islands", cities: [{ name: "San Jose", zip: "8427" }] },
  { name: "Eastern Samar", cities: [{ name: "Borongan City", zip: "6800" }] },
  { name: "Guimaras", cities: [{ name: "Jordan", zip: "5045" }] },
  { name: "Ifugao", cities: [{ name: "Lagawe", zip: "3600" }, { name: "Banaue", zip: "3601" }] },
  { name: "Ilocos Norte", cities: [{ name: "Laoag City", zip: "2900" }, { name: "Batac City", zip: "2906" }] },
  { name: "Ilocos Sur", cities: [{ name: "Vigan City", zip: "2700" }, { name: "Candon City", zip: "2710" }] },
  { name: "Iloilo", cities: [{ name: "Iloilo City", zip: "5000" }, { name: "Passi City", zip: "5037" }] },
  { name: "Isabela", cities: [{ name: "Ilagan City", zip: "3300" }, { name: "Cauayan City", zip: "3305" }, { name: "Santiago City", zip: "3311" }] },
  { name: "Kalinga", cities: [{ name: "Tabuk City", zip: "3800" }] },
  { name: "La Union", cities: [{ name: "San Fernando City", zip: "2500" }, { name: "Bauang", zip: "2501" }] },
  { name: "Laguna", cities: [{ name: "Santa Cruz", zip: "4009" }, { name: "Calamba City", zip: "4027" }, { name: "Binan City", zip: "4024" }, { name: "Santa Rosa City", zip: "4026" }, { name: "San Pablo City", zip: "4000" }, { name: "Cabuyao City", zip: "4025" }, { name: "Los Banos", zip: "4030" }] },
  { name: "Lanao del Norte", cities: [{ name: "Iligan City", zip: "9200" }, { name: "Tubod", zip: "9209" }] },
  { name: "Lanao del Sur", cities: [{ name: "Marawi City", zip: "9700" }] },
  { name: "Leyte", cities: [{ name: "Tacloban City", zip: "6500" }, { name: "Ormoc City", zip: "6541" }, { name: "Baybay City", zip: "6521" }] },
  { name: "Maguindanao del Norte", cities: [{ name: "Datu Odin Sinsuat", zip: "9601" }] },
  { name: "Maguindanao del Sur", cities: [{ name: "Buluan", zip: "9616" }] },
  { name: "Marinduque", cities: [{ name: "Boac", zip: "4900" }] },
  { name: "Masbate", cities: [{ name: "Masbate City", zip: "5400" }] },
  { name: "Metro Manila", cities: [
    { name: "Quezon City", zip: "1100" }, { name: "Manila", zip: "1000" }, { name: "Makati", zip: "1200" },
    { name: "Taguig", zip: "1634" }, { name: "Pasig", zip: "1600" }, { name: "Mandaluyong", zip: "1550" },
    { name: "Parañaque", zip: "1700" }, { name: "Las Piñas", zip: "1740" }, { name: "Muntinlupa", zip: "1770" },
    { name: "Pasay", zip: "1300" }, { name: "Marikina", zip: "1800" }, { name: "Valenzuela", zip: "1440" },
    { name: "Caloocan", zip: "1400" }, { name: "Malabon", zip: "1470" }, { name: "Navotas", zip: "1485" },
    { name: "San Juan", zip: "1500" }, { name: "Pateros", zip: "1620" }
  ] },
  { name: "Misamis Occidental", cities: [{ name: "Oroquieta City", zip: "7207" }, { name: "Ozamiz City", zip: "7200" }, { name: "Tangub City", zip: "7214" }] },
  { name: "Misamis Oriental", cities: [{ name: "Cagayan de Oro City", zip: "9000" }, { name: "Gingoog City", zip: "9014" }, { name: "El Salvador City", zip: "9017" }] },
  { name: "Mountain Province", cities: [{ name: "Bontoc", zip: "2616" }] },
  { name: "Negros Occidental", cities: [{ name: "Bacolod City", zip: "6100" }, { name: "Bago City", zip: "6101" }, { name: "Cadiz City", zip: "6121" }, { name: "Escalante City", zip: "6124" }, { name: "Himamaylan City", zip: "6108" }, { name: "Kabankalan City", zip: "6111" }, { name: "La Carlota City", zip: "6130" }, { name: "Sagay City", zip: "6122" }, { name: "San Carlos City", zip: "6127" }, { name: "Silay City", zip: "6116" }, { name: "Sipalay City", zip: "6113" }, { name: "Talisay City", zip: "6115" }, { name: "Victorias City", zip: "6119" }] },
  { name: "Negros Oriental", cities: [{ name: "Dumaguete City", zip: "6200" }, { name: "Bais City", zip: "6206" }, { name: "Bayawan City", zip: "6221" }, { name: "Canlaon City", zip: "6223" }, { name: "Guihulngan City", zip: "6214" }, { name: "Tanjay City", zip: "6204" }] },
  { name: "Northern Samar", cities: [{ name: "Catarman", zip: "6400" }] },
  { name: "Nueva Ecija", cities: [{ name: "Palayan City", zip: "3101" }, { name: "Cabanatuan City", zip: "3100" }, { name: "Gapan City", zip: "3105" }, { name: "Muñoz City", zip: "3119" }, { name: "San Jose City", zip: "3121" }] },
  { name: "Nueva Vizcaya", cities: [{ name: "Bayombong", zip: "3700" }] },
  { name: "Occidental Mindoro", cities: [{ name: "Mamburao", zip: "5106" }, { name: "San Jose", zip: "5100" }] },
  { name: "Oriental Mindoro", cities: [{ name: "Calapan City", zip: "5200" }, { name: "Puerto Galera", zip: "5203" }] },
  { name: "Palawan", cities: [{ name: "Puerto Princesa City", zip: "5300" }, { name: "El Nido", zip: "5313" }, { name: "Coron", zip: "5316" }] },
  { name: "Pampanga", cities: [{ name: "San Fernando City", zip: "2000" }, { name: "Angeles City", zip: "2009" }, { name: "Mabalacat City", zip: "2010" }, { name: "Guagua", zip: "2003" }] },
  { name: "Pangasinan", cities: [{ name: "Lingayen", zip: "2401" }, { name: "Dagupan City", zip: "2400" }, { name: "Alaminos City", zip: "2404" }, { name: "San Carlos City", zip: "2420" }, { name: "Urdaneta City", zip: "2428" }] },
  { name: "Quezon", cities: [{ name: "Lucena City", zip: "4301" }, { name: "Tayabas City", zip: "4327" }] },
  { name: "Quirino", cities: [{ name: "Cabarroguis", zip: "3400" }] },
  { name: "Rizal", cities: [{ name: "Antipolo City", zip: "1870" }, { name: "Cainta", zip: "1900" }, { name: "Taytay", zip: "1920" }, { name: "Binangonan", zip: "1940" }, { name: "San Mateo", zip: "1850" }] },
  { name: "Romblon", cities: [{ name: "Romblon", zip: "5500" }] },
  { name: "Samar", cities: [{ name: "Catbalogan City", zip: "6700" }, { name: "Calbayog City", zip: "6710" }] },
  { name: "Sarangani", cities: [{ name: "Alabel", zip: "9501" }] },
  { name: "Siquijor", cities: [{ name: "Siquijor", zip: "6225" }] },
  { name: "Sorsogon", cities: [{ name: "Sorsogon City", zip: "4700" }] },
  { name: "South Cotabato", cities: [{ name: "Koronadal City", zip: "9506" }, { name: "General Santos City", zip: "9500" }] },
  { name: "Southern Leyte", cities: [{ name: "Maasin City", zip: "6600" }] },
  { name: "Sultan Kudarat", cities: [{ name: "Isulan", zip: "9805" }, { name: "Tacurong City", zip: "9800" }] },
  { name: "Sulu", cities: [{ name: "Jolo", zip: "7400" }] },
  { name: "Surigao del Norte", cities: [{ name: "Surigao City", zip: "8400" }] },
  { name: "Surigao del Sur", cities: [{ name: "Tandag City", zip: "8300" }, { name: "Bislig City", zip: "8311" }] },
  { name: "Tarlac", cities: [{ name: "Tarlac City", zip: "2300" }] },
  { name: "Tawi-Tawi", cities: [{ name: "Bongao", zip: "7500" }] },
  { name: "Zambales", cities: [{ name: "Iba", zip: "2201" }, { name: "Olongapo City", zip: "2200" }, { name: "Subic", zip: "2209" }] },
  { name: "Zamboanga del Norte", cities: [{ name: "Dipolog City", zip: "7100" }, { name: "Dapitan City", zip: "7101" }] },
  { name: "Zamboanga del Sur", cities: [{ name: "Pagadian City", zip: "7016" }, { name: "Zamboanga City", zip: "7000" }] },
  { name: "Zamboanga Sibugay", cities: [{ name: "Ipil", zip: "7001" }] }
];
